variable "env" {}
variable "vpc" {}
variable "app" {}
variable "docdb" {}
variable "rds" {}
variable "kms_arn" {}
variable "default_vpc_id" {}
variable "default_vpc_cidr" {}
variable "bastion_cidr" {}
variable "default_vpc_rt_id" {}
variable "elasticache" {}
variable "rabbitmq" {}
variable "alb" {}
